apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-anagrafiche
  namespace: {{ .Release.Namespace }}
  labels:
    app: agata
    service: agata-anagrafiche
spec:
  ports:
    - port: {{ .Values.anagrafiche.service.port }}
      targetPort: {{ .Values.anagrafiche.service.targetPort }}
  selector:
    app: agata
    service: agata-anagrafiche
  type: {{ .Values.anagrafiche.service.type }}
