apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-env
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.frontend.config }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
