{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
{{- range .Values.ingress.routes }}
    - match: {{ .match | quote }}
      kind: Rule
      services:
        - name: {{ .service.name }}
          port: {{ .service.port }}
{{- if .middlewares }}
      middlewares:
{{- range .middlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace | default $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
  tls:
    certResolver: {{ .Values.ingress.tls.certResolver }}
{{- end }}
